/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.HospitalVisitors;

import Business.Organization.Organization;
import Business.RegularExpressionCheck;
import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Siddhi
 */
public class RecipientRegistrationForm extends javax.swing.JPanel {

    /**
     * Creates new form RecipientRegistrationForm
     */
    JPanel container;
    Organization organization;
    
    
    public RecipientRegistrationForm(JPanel container, Organization organization) {
        initComponents();
        this.container = container;
        this.organization = organization;
        groupButton1();
        groupButton2();

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        contactNumTextField = new javax.swing.JTextField();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        emailIdTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        signatureTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        corneasRdBtn = new javax.swing.JRadioButton();
        kidneyRdBtn = new javax.swing.JRadioButton();
        heartRdBtn = new javax.swing.JRadioButton();
        lungRdBtn = new javax.swing.JRadioButton();
        liverRdBtn = new javax.swing.JRadioButton();
        pancreasRdBtn = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Organ Recipient Form");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel4.setText("Blood Group");

        nameTextField.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N

        ageTextField.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N

        contactNumTextField.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N

        maleRadioBtn.setBackground(new java.awt.Color(255, 204, 204));
        maleRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        maleRadioBtn.setText("Male");

        femaleRadioBtn.setBackground(new java.awt.Color(255, 204, 204));
        femaleRadioBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        femaleRadioBtn.setText("Female");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel11.setText("Contact Number");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel13.setText("Email Id");

        emailIdTextField.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel14.setText("Address");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        addressTextArea.setRows(5);
        jScrollPane3.setViewportView(addressTextArea);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Signature");

        signatureTextField.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jLabel10.setText("Sex");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel12.setText("Which part needs to transplant");

        corneasRdBtn.setBackground(new java.awt.Color(255, 204, 204));
        corneasRdBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        corneasRdBtn.setText("Corneas");

        kidneyRdBtn.setBackground(new java.awt.Color(255, 204, 204));
        kidneyRdBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        kidneyRdBtn.setText("Kidney");

        heartRdBtn.setBackground(new java.awt.Color(255, 204, 204));
        heartRdBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        heartRdBtn.setText("Heart");

        lungRdBtn.setBackground(new java.awt.Color(255, 204, 204));
        lungRdBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        lungRdBtn.setText("Lung");

        liverRdBtn.setBackground(new java.awt.Color(255, 204, 204));
        liverRdBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        liverRdBtn.setText("Liver");

        pancreasRdBtn.setBackground(new java.awt.Color(255, 204, 204));
        pancreasRdBtn.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        pancreasRdBtn.setText("Pancreas");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O-positive", "O-negative ", "A-positive", "A-negative", "B-positive", "B-negative", "AB-positive", "AB-negative" }));

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("<< Back");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Submit");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Images/IMAGES/Recipient.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(962, 962, 962)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(252, 252, 252)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(corneasRdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(liverRdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pancreasRdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lungRdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kidneyRdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                    .addComponent(heartRdBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel9)
                        .addGap(56, 56, 56)
                        .addComponent(signatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(maleRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14)
                                            .addComponent(femaleRadioBtn))
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13)))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(contactNumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                        .addComponent(emailIdTextField))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(femaleRadioBtn)
                                .addComponent(pancreasRdBtn)
                                .addComponent(lungRdBtn))
                            .addComponent(maleRadioBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(contactNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(emailIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(corneasRdBtn)
                                    .addComponent(kidneyRdBtn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(liverRdBtn)
                                    .addComponent(heartRdBtn)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(signatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
//        Component[] componentArray ;
//        for(Component c : container.getComponents()){
//        if(c instanceof ManageHospitalVisitors){
//        ManageHospitalVisitors sysAdminwjp = (ManageHospitalVisitors) c;}
//        // sysAdminwjp.populateTree();
//        }
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sex="";
        if(maleRadioBtn.isSelected())
            sex = maleRadioBtn.getText();
        if(femaleRadioBtn.isSelected()) 
            sex = femaleRadioBtn.getText();

        String sign = signatureTextField.getText();     
        String name = nameTextField.getText();
        String contactNum = contactNumTextField.getText();
        String emailAdd = emailIdTextField.getText();
        
       if(name.equals("") || sex.equals("") || sign.equals("") || emailAdd.equals("") || contactNum.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all the details.");
            return;
        }
        
        int age;
        
        try
           {
        
            age =  Integer.parseInt(ageTextField.getText());
            
            if(age > 120 || age < 18){
                JOptionPane.showMessageDialog(null , "Please enter correct age.");
                ageTextField.setText("");
                 return;
            }
           }
           catch(NumberFormatException e)
           {
            JOptionPane.showMessageDialog(null , "Age should be numeric."); 
            ageTextField.setText("");
               return;
           }
           
         //check valid name
        if(!RegularExpressionCheck.findRE(name) || !RegularExpressionCheck.findRE(sign)){
            JOptionPane.showMessageDialog(null, "Please enter valid name.");
            return;
        }
        //check for valid emailId
        if(!RegularExpressionCheck.isValidEmailAddress(emailAdd)){
            JOptionPane.showMessageDialog(null, " Invalid Username." + 
                "Username should be an email-ID with '_' and '@' as the only allowed special characters but should not start with '_'");
            return;
        }
        //check valid phone number
        if(!RegularExpressionCheck.isValidPhoneNum(contactNum)){
            JOptionPane.showMessageDialog(null, " Invalid phonenumber." + 
                "Phone number should be 10 digit number between 0-9.");
            return;
        }
        
        if(!(corneasRdBtn.isSelected() || kidneyRdBtn.isSelected() || heartRdBtn.isSelected() ||
                lungRdBtn.isSelected() || liverRdBtn.isSelected() || pancreasRdBtn.isSelected())){
            JOptionPane.showMessageDialog(null, "Please select a organ for transplant.");
            return;
        }
            Object bloodGroup = jComboBox1.getSelectedItem();

            String address = addressTextArea.getText();
            //String date = dateTextField.getText();
            String organ;
            
            if(corneasRdBtn.isSelected())
                organ = corneasRdBtn.getText();
            else if(kidneyRdBtn.isSelected())
                organ = kidneyRdBtn.getText();
            else if(heartRdBtn.isSelected())
                organ = heartRdBtn.getText();
            else if(lungRdBtn.isSelected())
                organ = lungRdBtn.getText();
            else if(liverRdBtn.isSelected())
                organ = liverRdBtn.getText();
            else 
                organ = pancreasRdBtn.getText();
            
            
            if(organization != null && organization.getRecipientDirectory() != null){
                organization.getRecipientDirectory().addRecipient(name, age, sex, (String) bloodGroup,
                        contactNum, address, sign, emailAdd, organ);
                JOptionPane.showMessageDialog(null, "You have registered successfully.");
                
                clearFields();
                container.remove(this);
                CardLayout layout = (CardLayout) container.getLayout();
                layout.previous(container);
            }
            
            //JOptionPane.showMessageDialog(null, "Organ Recipient Form Created Successfully");
            //jTextArea1.setText("");
          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void groupButton1() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(maleRadioBtn);
        buttonGroup.add(femaleRadioBtn);
    }
    
    private void groupButton2() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(corneasRdBtn);
        buttonGroup.add(kidneyRdBtn);
        buttonGroup.add(heartRdBtn);
        buttonGroup.add(lungRdBtn);
        buttonGroup.add(liverRdBtn);
        buttonGroup.add(pancreasRdBtn);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField contactNumTextField;
    private javax.swing.JRadioButton corneasRdBtn;
    private javax.swing.JTextField emailIdTextField;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JRadioButton heartRdBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JRadioButton kidneyRdBtn;
    private javax.swing.JRadioButton liverRdBtn;
    private javax.swing.JRadioButton lungRdBtn;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JRadioButton pancreasRdBtn;
    private javax.swing.JTextField signatureTextField;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
            nameTextField.setText("");
            ageTextField.setText("");
            contactNumTextField.setText("");
            emailIdTextField.setText("");
            addressTextArea.setText("");
            signatureTextField.setText("");
    }
}