/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Machines.Product;  
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Priyanka Malpekar
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Product product;
    
    public CreateJPanel(Product product) {
        initComponents();
        this.product=product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        availNumTextField = new javax.swing.JTextField();
        descriptionTextField = new javax.swing.JTextField();
        colourTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        speedTextField = new javax.swing.JTextField();
        wheelsTextField = new javax.swing.JTextField();
        doorsTextField = new javax.swing.JTextField();
        seatsTextField = new javax.swing.JTextField();
        fuelTextField = new javax.swing.JTextField();
        regNumTextField = new javax.swing.JTextField();
        plateNumTextField = new javax.swing.JTextField();
        engineTextField = new javax.swing.JTextField();
        lookTextField = new javax.swing.JTextField();
        CreateBtn = new javax.swing.JButton();
        CarUpload = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        PathDisplay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Enter Product Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 342, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Price:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Availability Number:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Description:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        nameTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        nameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 105, 25));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Colour:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Model:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("Speed:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Wheels:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Doors:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("Seats:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setText("Fuel:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("RegNum:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("PlateNum:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Engine:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("Look:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, 19));

        priceTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        priceTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });
        add(priceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 105, 25));

        availNumTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        availNumTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(availNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 105, 25));

        descriptionTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        descriptionTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(descriptionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 105, 25));

        colourTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        colourTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(colourTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 105, 25));

        modelTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        modelTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(modelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 105, 25));

        speedTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        speedTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        speedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speedTextFieldActionPerformed(evt);
            }
        });
        add(speedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 105, 25));

        wheelsTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        wheelsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(wheelsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 105, 25));

        doorsTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        doorsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        doorsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorsTextFieldActionPerformed(evt);
            }
        });
        add(doorsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 105, 25));

        seatsTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        seatsTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        seatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsTextFieldActionPerformed(evt);
            }
        });
        add(seatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 105, 25));

        fuelTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        fuelTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fuelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTextFieldActionPerformed(evt);
            }
        });
        add(fuelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 105, 25));

        regNumTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        regNumTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNumTextFieldActionPerformed(evt);
            }
        });
        add(regNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 105, 25));

        plateNumTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        plateNumTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plateNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateNumTextFieldActionPerformed(evt);
            }
        });
        add(plateNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 105, 25));

        engineTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        engineTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        engineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTextFieldActionPerformed(evt);
            }
        });
        add(engineTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 105, 25));

        lookTextField.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        lookTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lookTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookTextFieldActionPerformed(evt);
            }
        });
        add(lookTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 105, 25));

        CreateBtn.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        CreateBtn.setText("Create");
        CreateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CreateBtn.setBorderPainted(false);
        CreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateBtnActionPerformed(evt);
            }
        });
        add(CreateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 305, 120, 30));

        CarUpload.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        CarUpload.setText("Browse Details");
        CarUpload.setBorder(null);
        CarUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarUploadActionPerformed(evt);
            }
        });
        add(CarUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 337, 120, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Path:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 50, 20));

        PathDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(PathDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 360, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void doorsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doorsTextFieldActionPerformed

    private void seatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatsTextFieldActionPerformed

    private void fuelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTextFieldActionPerformed

    private void regNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNumTextFieldActionPerformed

    private void plateNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateNumTextFieldActionPerformed

    private void engineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineTextFieldActionPerformed

    private void lookTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lookTextFieldActionPerformed

    private void CreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateBtnActionPerformed
        // TODO add your handling code here:
        //Binding the user input to the product object
        product.setName(nameTextField.getText());
        product.setPrice(priceTextField.getText());
        product.setAvailNum(availNumTextField.getText());
        product.setDescription(descriptionTextField.getText());
        product.setColour(colourTextField.getText());
        product.setModel(modelTextField.getText());
        product.setSpeed(speedTextField.getText());
        product.setWheels(wheelsTextField.getText());
        product.setDoors(doorsTextField.getText());
        product.setSeats(seatsTextField.getText());
        product.setFuel(fuelTextField.getText());
        product.setRegNum(regNumTextField.getText());
        product.setPlateNum(plateNumTextField.getText());
        product.setEngine(engineTextField.getText());
        product.setLook(lookTextField.getText());
        product.setPath(PathDisplay.getText());
        //Prompt user that product was successfully created
        
        JOptionPane.showMessageDialog(null,"Create Product Successfully ");
        
    }//GEN-LAST:event_CreateBtnActionPerformed

    private void CarUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarUploadActionPerformed
      JFileChooser chooser=new JFileChooser();
      chooser.showOpenDialog(null);
      File f=chooser.getSelectedFile();
      String filename=f.getAbsolutePath();
      PathDisplay.setText(filename);
    }//GEN-LAST:event_CarUploadActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void speedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speedTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarUpload;
    private javax.swing.JButton CreateBtn;
    private javax.swing.JLabel PathDisplay;
    private javax.swing.JTextField availNumTextField;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JTextField doorsTextField;
    private javax.swing.JTextField engineTextField;
    private javax.swing.JTextField fuelTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lookTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField plateNumTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField regNumTextField;
    private javax.swing.JTextField seatsTextField;
    private javax.swing.JTextField speedTextField;
    private javax.swing.JTextField wheelsTextField;
    // End of variables declaration//GEN-END:variables
}
