/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AwarenessCamps;

import Business.Account.Account;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Network.Network;
import Business.Organization.GovernmentFunding;
import Business.Organization.Organization;
import Business.Organization.VisitorOrganization;
import Business.Person.AwarenessEvent;
import Business.Person.Visitor;
import Business.Person.VisitorDirectory;
import Business.RegularExpressionCheck;
import Business.WorkQueue.FundWorkRequest;
import java.awt.CardLayout;
import java.awt.Font;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.GovernmentFunding.FundRequestStatusJPanel;

/**
 *
 * @author Anuja
 */
public class AwarenessCamps extends javax.swing.JPanel {

    EcoSystem system;
    JPanel rightPanel;
    VisitorDirectory vd = new VisitorDirectory();
    private Account userAccount;
    private Enterprise enterprise;
    
    /**
     * Creates new form AwarenessCamps
     */
    public AwarenessCamps(JPanel rightPanel, EcoSystem system, Account account,Enterprise enterprise ) {
        initComponents();
        this.rightPanel = rightPanel;
        this.system = system;
        this.userAccount = account;
        this.enterprise=enterprise;
    
        
        populateTable();
        populateNetworkComboBox();
        eventInfoJTable.getTableHeader().setFont(new Font("Times New Roman" , Font.ITALIC,23));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        createEvent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventInfoJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eventNameTxt = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txtFunds = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resultStatus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Select the city");
        add(jLabel1);
        jLabel1.setBounds(96, 312, 143, 28);

        networkJComboBox.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(networkJComboBox);
        networkJComboBox.setBounds(310, 310, 147, 33);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Select Date");
        add(jLabel2);
        jLabel2.setBounds(132, 401, 115, 28);

        createEvent.setBackground(new java.awt.Color(153, 204, 255));
        createEvent.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        createEvent.setText("Create Event");
        createEvent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEventActionPerformed(evt);
            }
        });
        add(createEvent);
        createEvent.setBounds(105, 549, 361, 35);

        eventInfoJTable.setBackground(new java.awt.Color(255, 204, 204));
        eventInfoJTable.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        eventInfoJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Event Name", "Network", "Date", "Funds "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(eventInfoJTable);
        if (eventInfoJTable.getColumnModel().getColumnCount() > 0) {
            eventInfoJTable.getColumnModel().getColumn(0).setResizable(false);
            eventInfoJTable.getColumnModel().getColumn(1).setResizable(false);
            eventInfoJTable.getColumnModel().getColumn(2).setResizable(false);
            eventInfoJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(54, 99, 896, 158);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Scheduled Event Details");
        add(jLabel3);
        jLabel3.setBounds(54, 53, 247, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Event Name");
        add(jLabel4);
        jLabel4.setBounds(123, 352, 124, 28);

        eventNameTxt.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        add(eventNameTxt);
        eventNameTxt.setBounds(310, 350, 147, 33);
        add(jDateChooser2);
        jDateChooser2.setBounds(310, 397, 147, 32);

        txtFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFundsActionPerformed(evt);
            }
        });
        add(txtFunds);
        txtFunds.setBounds(309, 448, 147, 33);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Request Funds");
        add(jLabel5);
        jLabel5.setBounds(96, 447, 151, 28);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("$");
        add(jLabel6);
        jLabel6.setBounds(279, 447, 18, 28);

        resultStatus.setBackground(new java.awt.Color(153, 204, 255));
        resultStatus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        resultStatus.setText("Fund Request Status");
        resultStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resultStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultStatusActionPerformed(evt);
            }
        });
        add(resultStatus);
        resultStatus.setBounds(105, 602, 361, 35);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Images/IMAGES/Donate.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(660, 290, 510, 400);
        add(jLabel8);
        jLabel8.setBounds(580, 300, 460, 340);
    }// </editor-fold>//GEN-END:initComponents

    public void sendEmail(String email, String eventName, String dateOfEvent){
            final String to = email;
            boolean sessionDebug=false;
            String from = "sidjonas12345@gmail.com"; 
            String host = "smtp.gmail.com";
            String user="sidjonas12345@gmail.com";
            String pass = "Smart@1995";
            Properties properties = System.getProperties();  
            properties.setProperty("mail.smtp.host", host); properties.put("mail.smtp.starttls.required", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host",host);  
            properties.put("mail.smtp.port", "587");  
            properties.put("mail.smtp.auth", "true");  
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());  
            Session session;
            session = Session.getDefaultInstance(properties,  null);
            session.setDebug(sessionDebug);
            try{
            MimeMessage message = new MimeMessage(session);  
            message.setFrom(new InternetAddress(from));  
            message.setRecipient(Message.RecipientType.TO,new InternetAddress(to));  
            InternetAddress address;
            address = new InternetAddress(to);
            message.setSubject("Did you know?");  
            message.setText("Please visit the awareness camp titled "+eventName+"on "+dateOfEvent+"in "+networkJComboBox.getItemAt(networkJComboBox.getSelectedIndex())+" to learn more about the important of organ donation. Please RSVP");  
            Transport transport = session.getTransport("smtp");
            transport.connect(host,user,pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            //JOptionPane.showMessageDialog(null, "Please check your email for further details!");
            }
            
            catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Error!");
            }
    }
    
    
    
    
    private void createEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEventActionPerformed
        
        Network city =  (Network) networkJComboBox.getSelectedItem();
        String name = eventNameTxt.getText();
        Date date = jDateChooser2.getDate();
        float Funds = 0;
        //Funds = Float.parseFloat(txtFunds.getText());
        Date today = new Date();
        Date currentDate = new java.sql.Date(today.getTime());
        
        //Validate Event field
        if(!RegularExpressionCheck.isValidEvent(name)){
            JOptionPane.showMessageDialog(null, " Invalid Event Name!!");
            return;
        }
        
        
        
        //Adding If loop for date field validation
           try{
            if (date.compareTo(currentDate) < 0) {
            //System.out.println("Date1 is before Date2");
            JOptionPane.showMessageDialog(null,"Please choose future date!! ");
            return;
            
            }
        
           }catch(NullPointerException e)
           {
           JOptionPane.showMessageDialog(null,"Please fill all details. ");
           return;
           
           
           }
         
        //Exception handling
        try
        {
            Funds = Float.parseFloat(txtFunds.getText());
            txtFunds.setText("");
            //return;
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid funds.");
            txtFunds.setText("");
            return ;
        }
        
 
        
        
        if(name.equals("") && date == null && city.equals(null)){
            JOptionPane.showMessageDialog(null, "Please fill all details.");
            return;
        }
        
        
       
        if(system != null){
            for(Visitor v :vd.getVisitorList()){
                sendEmail(v.getEmail(), eventNameTxt.getText(), String.valueOf(date));
            }
            for(Network n: system.getNetworkList()){
                if(n.getName().equals(String.valueOf(networkJComboBox.getItemAt(networkJComboBox.getSelectedIndex())))){
                  for(Enterprise e:   n.getEnterpriseDirectory().getEnterpriseList()){
                    for (Organization o: e.getOrganizationDirectory().getOrganizationList()){
                        if(o instanceof VisitorOrganization){
//                        for(Visitor v: o.getVd().getVisitorList()){
//                            sendEmail(v.getEmail(), eventNameTxt.getText(), String.valueOf(date));  
//                        }
                    }
                    }
                  }
                }
            }
            
            FundWorkRequest request = new FundWorkRequest();
            request.setMessage("Please approve the funds");
            request.setSender(userAccount);
            request.setStatus("Sent");
            request.setNGO(eventNameTxt.getText());
            request.setFunds(Funds);
            request.setEventName(name);
            
            
            //System.out.println(request.getFunds());
            
            Organization o= null;
         for(Network n: system.getNetworkList()){
           
            for(Enterprise e:n.getEnterpriseDirectory().getEnterpriseList()){
                if(e instanceof GovernmentEnterprise){
                   for(Organization org:  e.getOrganizationDirectory().getOrganizationList()){
                       if(org instanceof GovernmentFunding){
                           
                           //System.out.println("INSIDE AWARENESSCAMP IF LOOP GovernmentFunding ORGANISATION ");
                           o=org;
                           
                       }
                   }
                }
            }
        }
       if(o!=null){
            o.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);}
        
        
        
        //AWRENESS 
            AwarenessEvent event = system.createEvent();
            event.setEventName(name);
            event.setNetworkName(city.getName());
            event.setEventDate(date);
            event.setFunds(Funds);
            JOptionPane.showMessageDialog(null, "Awareness event created successfully.");
            eventNameTxt.setText("");
            jDateChooser2.setDate(null);
            txtFunds.setText("");
            populateTable();
        }
    }//GEN-LAST:event_createEventActionPerformed

    private void txtFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFundsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFundsActionPerformed

    private void resultStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultStatusActionPerformed
        
        FundRequestStatusJPanel fundRequestJPanel = new FundRequestStatusJPanel(rightPanel, enterprise,userAccount);
        rightPanel.add("FundRequestStatusJPanel", fundRequestJPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_resultStatusActionPerformed


    private void populateNetworkComboBox(){
        networkJComboBox.removeAllItems();
        
        for (Network network : system.getNetworkList()){
            networkJComboBox.addItem(network);
        }
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) eventInfoJTable.getModel();

        model.setRowCount(0);
        if(system != null && system.getEventList() != null){
            for (AwarenessEvent event : system.getEventList()) {
                Object[] row = new Object[4];
                row[0] = event.getEventName();
                row[1] = event.getNetworkName();
                row[2] = event.getEventDate();
                row[3] = event.getFunds();

                model.addRow(row);
            }
        }
 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEvent;
    private javax.swing.JTable eventInfoJTable;
    private javax.swing.JTextField eventNameTxt;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JButton resultStatus;
    private javax.swing.JTextField txtFunds;
    // End of variables declaration//GEN-END:variables
}
