/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.GovernmentFunding;

import Business.Account.Account;
import Business.Role.GovernmentRole;
import Business.Role.LabAssistantRole;
import Business.Role.LabRole;
import Business.WorkQueue.FundWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Siddhi
 */
public class FundApprovalJPanel extends javax.swing.JPanel {
    JPanel rightPanel;
    FundWorkRequest request;
    Account account;
    /**
     * Creates new form FundApprovalJPanel
     */
    public FundApprovalJPanel(JPanel rightPanel, FundWorkRequest request, Account account) {
        initComponents();
         this.rightPanel= rightPanel;
        this.request=request;
        this.account=account;
        populatefunds();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFundReq = new javax.swing.JTextField();
        fileUploadLabel = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Fund Requested");

        txtFundReq.setEditable(false);
        txtFundReq.setEnabled(false);
        txtFundReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFundReqActionPerformed(evt);
            }
        });

        btnApprove.setBackground(new java.awt.Color(255, 204, 204));
        btnApprove.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnDecline.setBackground(new java.awt.Color(255, 204, 204));
        btnDecline.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDecline.setText("Decline");
        btnDecline.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("$");

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Images/IMAGES/Approved.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(fileUploadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(762, 762, 762))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtFundReq, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 916, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(fileUploadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFundReq, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApprove)
                    .addComponent(btnDecline, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(384, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        if(txtFundReq.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            return;
        }
        else{
            request.setApproval(txtFundReq.getText());
            //System.out.println("HERE-------        "+request.getSender().toString());
            //email to patient
            boolean sessionDebug=false;
            final String to = request.getSender().toString();//this needs to be an email address
            System.out.println("TO ADDRESS    "+to);
            String from = "sidjonas12345@gmail.com";
            String host = "smtp.gmail.com";
            String user="sidjonas12345@gmail.com";
            String pass = "Smart@1995";//we have to type the real password here for it to work
            //if it is gmail we have to enable less secure apps
            Properties properties = System.getProperties();
            properties.setProperty("mail.smtp.host", host); properties.put("mail.smtp.starttls.required", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host",host);
            properties.put("mail.smtp.port", "587");
            properties.put("mail.smtp.auth", "true");
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session session;
            session = Session.getDefaultInstance(properties,  null);
            session.setDebug(sessionDebug);
            try{
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(from));
                message.setRecipient(Message.RecipientType.TO,new InternetAddress(to));
                InternetAddress address;
                address = new InternetAddress(to);
                message.setSubject("Your Fund Approval Status");
                message.setText("Congratulations! Your Fund Request is Approved");
                //message.setFileName(request.getFileupload());
                Transport transport = session.getTransport("smtp");
                transport.connect(host,user,pass);
                transport.sendMessage(message, message.getAllRecipients());
                transport.close();
            }
            catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Error!");

            }
            //request.setFundstatus("Approved");
            request.setStatus("Approved");
            //System.out.println(request.getFundstatus());
            //System.out.println(request.getStatus());
            JOptionPane.showMessageDialog(null, "Funds Approved");
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void txtFundReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFundReqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFundReqActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
            if(txtFundReq.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a comment!");
            return;
        }
        else{
            request.setApproval(txtFundReq.getText());

            //email to patient
            boolean sessionDebug=false;
            final String to = request.getSender().toString();//this needs to be an email address
            String from = "sidjonas12345@gmail.com";
            String host = "smtp.gmail.com";
            String user="sidjonas12345@gmail.com";
            String pass = "Smart@1995";//we have to type the real password here for it to work
            //if it is gmail we have to enable less secure apps
            Properties properties = System.getProperties();
            properties.setProperty("mail.smtp.host", host); properties.put("mail.smtp.starttls.required", "true");
            properties.put("mail.smtp.starttls.enable", "true");
            properties.put("mail.smtp.host",host);
            properties.put("mail.smtp.port", "587");
            properties.put("mail.smtp.auth", "true");
            java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
            Session session;
            session = Session.getDefaultInstance(properties,  null);
            session.setDebug(sessionDebug);
            try{
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(from));
                message.setRecipient(Message.RecipientType.TO,new InternetAddress(to));
                InternetAddress address;
                address = new InternetAddress(to);
                message.setSubject("Your Fund Approval Status");
                message.setText("Sorry! Your Fund Request is Declined!!");
                //message.setFileName(request.getFileupload());
                Transport transport = session.getTransport("smtp");
                transport.connect(host,user,pass);
                transport.sendMessage(message, message.getAllRecipients());
                transport.close();
            }
            catch(Exception e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Error!");

            }
            //request.setFundstatus("Approved");
            request.setStatus("Declined");
            //System.out.println(request.getFundstatus());
            //System.out.println(request.getStatus());
            JOptionPane.showMessageDialog(null, "Funds Declined");
        }
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         rightPanel.remove(this);
        Component[] componentArray = rightPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        GovermentFundingJPanel dwjp = (GovermentFundingJPanel) component;
        if(account.getRole() instanceof GovernmentRole)
        dwjp.populateTableEnterprise();
        
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDecline;
    private javax.swing.JLabel fileUploadLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFundReq;
    // End of variables declaration//GEN-END:variables

    private void populatefunds() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        //FundWorkRequest request = new FundWorkRequest();
        System.out.println("FUND APPROVAL JPANEL : "+request.getFunds());
        txtFundReq.setText(String.valueOf(request.getFunds()));
    
    
    
    
    
    }
}
